whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_for_in = false
conditional_to_if = false
separate_kwargs_with_semicolon = true
whitespace_in_kwargs = false
trailing_comma = false
margin = 1000