[deps]
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Mads = "d6bdc55b-bd94-5012-933c-1f73fc2ee992"
NMFk = "e40cd9e2-a1df-5d90-a1fa-603fdc3dbdd8"

[sources]
NMFk = {path = ".."}

[compat]
DocumentFunction = "1.6"
Documenter = "1"
Mads = "1.7"
NMFk = "1.5"
julia = "1.12"
